Dogpad/config/routes.rb
Dogpad::Application.routes.draw do
  
  resources :breeders

  resources :addresses

  resources :address_cats

  resources :dogs do
    resources :addresses
    resources :breeders
  end

  root :to=>'home#index', :as=>"home"
  

end

Dogpad/app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :AddressCat
  has_many :Breeders
  
  attr_accessible :city, :company, :country, :first_name, :last_name, 
                  :mail, :mobile, :phone, :street, :web, :zip, :AddressCat_id, :AddressCat
                  
  validates :AddressCat_id, :presence=>true, :numericality=>true
end

Dogpad/app/models/address_cat.rb
class AddressCat < ActiveRecord::Base
  has_many :Addresses
  
  attr_accessible :name
  
  validates :name, :presence=>true
end

Dogpad/app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :Gender
  belongs_to :Nutered
  belongs_to :Breeder
  
  attr_accessible :breed, :dob, :dod, :height, :weight, :name, :Breeder_id,
                  :Gender_id, :Nutered_id, :Gender, :Nutered
  
  validates :name, :presence=>true
  validates_numericality_of :height, :integer_only=>true, :allow_blank=>true
  validates_numericality_of :weight, :allow_blank=>true
end

Dogpad/app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :name
end

Dogpad/app/models/nutered.rb
class Nutered < ActiveRecord::Base
  attr_accessible :name
end

Dogpad/app/controllers/address_cats_controller.rb
class AddressCatsController < ApplicationController
  # GET /address_cats
  # GET /address_cats.json
  def index
    @address_cats = AddressCat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @address_cats }
    end
  end

  # GET /address_cats/1
  # GET /address_cats/1.json
  def show
    @address_cat = AddressCat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address_cat }
    end
  end

  # GET /address_cats/new
  # GET /address_cats/new.json
  def new
    @address_cat = AddressCat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address_cat }
    end
  end

  # GET /address_cats/1/edit
  def edit
    @address_cat = AddressCat.find(params[:id])
  end

  # POST /address_cats
  # POST /address_cats.json
  def create
    @address_cat = AddressCat.new(params[:address_cat])

    respond_to do |format|
      if @address_cat.save
        format.html { redirect_to @address_cat, notice: 'Address cat was successfully created.' }
        format.json { render json: @address_cat, status: :created, location: @address_cat }
      else
        format.html { render action: "new" }
        format.json { render json: @address_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /address_cats/1
  # PUT /address_cats/1.json
  def update
    @address_cat = AddressCat.find(params[:id])

    respond_to do |format|
      if @address_cat.update_attributes(params[:address_cat])
        format.html { redirect_to @address_cat, notice: 'Address cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_cats/1
  # DELETE /address_cats/1.json
  def destroy
    @address_cat = AddressCat.find(params[:id])
    @address_cat.destroy

    respond_to do |format|
      format.html { redirect_to address_cats_url }
      format.json { head :no_content }
    end
  end
end

Dogpad/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

Dogpad/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_dogs
  
  def get_dogs
    logger.debug "*** Get Dogs ***"
    @dogs = Dog.all
    
    logger.debug "*** Dog id #{params[:id]}***"
    if !params[:id].blank?
      dog_id = params[:id].to_i
      @selected_dog = Dog.find(dog_id)
    end
  end
end

Dogpad/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # GET /dogs
  # GET /dogs.json
  def index
    #@dogs = Dog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dogs }
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/new
  # GET /dogs/new.json
  def new
    @dog = Dog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
    
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(params[:dog])

    respond_to do |format|
      if @dog.save
        format.html { redirect_to edit_dog_path(@dog) }
        format.json { render json: @dog, status: :created, location: @dog }
      else
        format.html { render action: "new" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    @dog = Dog.find(params[:id])

    respond_to do |format|
      if @dog.update_attributes(params[:dog])
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end
end

Dogpad/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dogs = Dog.all
  end
  
end

Dogpad/app/helpers/address_cats_helper.rb
module AddressCatsHelper
end

Dogpad/app/helpers/addresses_helper.rb
module AddressesHelper
end

Dogpad/app/helpers/application_helper.rb
module ApplicationHelper
end

Dogpad/app/helpers/dogs_helper.rb
module DogsHelper
end

Dogpad/app/views/address_cats/_form.html.erb
<%= simple_form_for(@address_cat) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Dogpad/app/views/address_cats/edit.html.erb
<h1>Editing address_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_cat %> |
<%= link_to 'Back', address_cats_path %>

Dogpad/app/views/address_cats/index.html.erb
<h1>Listing address_cats</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @address_cats.each do |address_cat| %>
  <tr>
    <td><%= address_cat.name %></td>
    <td><%= link_to 'Show', address_cat %></td>
    <td><%= link_to 'Edit', edit_address_cat_path(address_cat) %></td>
    <td><%= link_to 'Destroy', address_cat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address cat', new_address_cat_path %>

Dogpad/app/views/address_cats/new.html.erb
<h1>New address_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', address_cats_path %>

Dogpad/app/views/address_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @address_cat.name %>
</p>


<%= link_to 'Edit', edit_address_cat_path(@address_cat) %> |
<%= link_to 'Back', address_cats_path %>

Dogpad/app/views/addresses/_form.html.erb
<%= simple_form_for(@address) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :street %>
    <%= f.input :zip %>
    <%= f.input :city %>
    <%= f.input :country %>
    <%= f.input :phone %>
    <%= f.input :mobile %>
    <%= f.input :mail %>
    <%= f.input :web %>
    <%= f.association :AddressCat %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Dogpad/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

Dogpad/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Company</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Street</th>
    <th>Zip</th>
    <th>City</th>
    <th>Country</th>
    <th>Phone</th>
    <th>Mobile</th>
    <th>Mail</th>
    <th>Web</th>
    <th>Addresscat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.company %></td>
    <td><%= address.first_name %></td>
    <td><%= address.last_name %></td>
    <td><%= address.street %></td>
    <td><%= address.zip %></td>
    <td><%= address.city %></td>
    <td><%= address.country %></td>
    <td><%= address.phone %></td>
    <td><%= address.mobile %></td>
    <td><%= address.mail %></td>
    <td><%= address.web %></td>
    <td><%= address.AddressCat %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

Dogpad/app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

Dogpad/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @address.company %>
</p>

<p>
  <b>First name:</b>
  <%= @address.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @address.last_name %>
</p>

<p>
  <b>Street:</b>
  <%= @address.street %>
</p>

<p>
  <b>Zip:</b>
  <%= @address.zip %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>

<p>
  <b>Country:</b>
  <%= @address.country %>
</p>

<p>
  <b>Phone:</b>
  <%= @address.phone %>
</p>

<p>
  <b>Mobile:</b>
  <%= @address.mobile %>
</p>

<p>
  <b>Mail:</b>
  <%= @address.mail %>
</p>

<p>
  <b>Web:</b>
  <%= @address.web %>
</p>

<p>
  <b>Addresscat:</b>
  <%= @address.AddressCat %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

Dogpad/app/views/dogs/_form.html.erb
<%= simple_form_for(@dog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.input :height %>
		<%= f.input :weight %>
    <%= f.input :dob %>
    <%= f.input :dod %>
    <%= f.association :Gender %>
    <%= f.association :Nutered %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Dogpad/app/views/dogs/edit.html.erb
<h1><%=@dog.name%></h1>

<%= render 'form' %>

Dogpad/app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Breed</th>
    <th>Height</th>
    <th>Dob</th>
    <th>Dod</th>
    <th>Gender</th>
    <th>Nutered</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dogs.each do |dog| %>
  <tr>
    <td><%= dog.name %></td>
    <td><%= dog.breed %></td>
    <td><%= dog.height %></td>
    <td><%= dog.dob %></td>
    <td><%= dog.dod %></td>
    <td><%= dog.Gender %></td>
    <td><%= dog.Nutered %></td>
    <td><%= link_to 'Show', dog %></td>
    <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
    <td><%= link_to 'Destroy', dog, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dog', new_dog_path %>

Dogpad/app/views/dogs/new.html.erb
<h1>Ny hund</h1>

<%= render 'form' %>

Dogpad/app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dog.name %>
</p>

<p>
  <b>Breed:</b>
  <%= @dog.breed %>
</p>

<p>
  <b>Height:</b>
  <%= @dog.height %>
</p>

<p>
  <b>Dob:</b>
  <%= @dog.dob %>
</p>

<p>
  <b>Dod:</b>
  <%= @dog.dod %>
</p>

<p>
  <b>Gender:</b>
  <%= @dog.Gender %>
</p>

<p>
  <b>Nutered:</b>
  <%= @dog.Nutered %>
</p>

Dogpad/app/views/home/index.html.erb
<h1>Startsida</h1>

Dogpad/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogpad</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Dogpad</a>
      <div class="nav-collapse">
        <ul class="nav">
					<li class="dropdown">
						    <a href="#"
						          class="dropdown-toggle"
						          data-toggle="dropdown">
						          Hundar
						          <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu">
									<% if !@dogs.blank? %>
										<% @dogs.each do |dog| %>
									  	<li><%= link_to dog.name, edit_dog_path(dog) %></li
										<% end %>
									<% end %>
						    </ul>
					</li>
				</ul>
			<li><%= link_to 'Ny hund', new_dog_path %></li>
      <li><%= link_to "Kontakta oss" %></li>
      <li><%= link_to "Inloggad som" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
	<div class="span2">	
		<%= render :partial=>'partials/menu'%>
	</div>
<div class="span7">
	<%= yield %>
</div>
<div class="span3">
	<h2>Reklam</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
</div>
</body>
</html>

Dogpad/app/views/partials/_menu.html.erb
<br />
<ul class="nav nav-list">
  <li class="active">
    <%= link_to "Hem", "home" %>
  </li>
  <li class="nav-header">
		<% if !@selected_dog.blank? %>
			<%= @selected_dog.name %>
		<% end %>
	</li>
	<% if !@selected_dog.blank? %>
		<% if !@selected_dog.Breeder_id.blank? %>
			<li><%= link_to "Uppfödare", dog_breeder_path(@selected_dog.id) %></li>
		<% else %>
			<li><%= link_to "Lägg till uppfödare", new_dog_breeder_path(@selected_dog.id)%>
		<% end %>
		<li><a href="#">Försäkringsbolag</a></li>
		<li class="nav-header">Verktyg</li>
		<li><%= link_to "Adresser", addresses_path %></li>
	<% end %>
</ul>